spring:
  profiles:
    active: dev
  flyway:
    baselineOnMigrate: true #项目进行后加入flyway，需要这个参数

mybatis:
  mapper.locations.fun: classpath*:mapping/*.xml
  type.aliases.package.fun: org.study.mybatis.dao.entity

server:
  port: 9010
